
namespace CO {
	constexpr auto Menu_Pickup_CollectableEasterEgg = 0x401A30;
	constexpr auto ClientUpdate = 0x303380;
	constexpr auto ClientUpdate_Sleeping = 0x302FF0;
	constexpr auto cursor_get_visible = 0x1828E80;
	constexpr auto get_Entity = 0x52C940; // localplayer
	constexpr auto Refract = 0x5C8080;
	constexpr auto SendSignalBroadcast = 0x434230;
	constexpr auto Magnitude2D = 0x1D73150;
	constexpr auto GetJumpHeight = 0x308980;
	constexpr auto MathfAbs = 0x183AD80;
	constexpr auto MathfMax = 0x183B950;
	constexpr auto GetHeight = 0x3081B0;
	constexpr auto GetRadius = 0x309E40;
	constexpr auto CheckCapsule = 0x2183AD0; // public static bool CheckCapsule(Vector3 start, Vector3 end, float radius, int layerMask, QueryTriggerInteraction queryTriggerInteraction) { }
	constexpr auto EffectRun = 0x97BC90; // Effect.client
	constexpr auto RebuildAll = 0xB30710;
	constexpr auto GetMaxSpeed = 0x308B20;
	constexpr auto DoFixedUpdate = 0xB39840;
	constexpr auto CanAffordUpgrade = 0x58A390;
	constexpr auto CanChangeToGrade = 0x58A560;
	constexpr auto IsUpgradeBlocked = 0x58C850;
	constexpr auto get_jumped = 0x1D0C050;
	constexpr auto get_velocity = 0x21882E0;
	constexpr auto set_velocity = 0x2188800;
	constexpr auto get_rotation = 0x7366D0; // playereyes
	constexpr auto Play = 0x76E070; // ViewModel
	constexpr auto GetRandomVelocity = 0x54D650;
	constexpr auto Client = 0x31BF570; // ConVar.Client_TypeInfo
	constexpr auto CreateEffect = 0x96FCE0;
	constexpr auto UpgradeToGrade = 0x58DB20;
	constexpr auto AddPunch = 0x438240;
	constexpr auto MoveTowards = 0x208E030;
	constexpr auto Jump = 0xB3BA40;
	constexpr auto Total = 0x3E1F80; // DamageTypeList
	constexpr auto IsDucked = 0x30C1F0;
	constexpr auto PropertyToId = 0x18DC800;
	constexpr auto VisUpdateUsingCulling = 0x31C290;
	constexpr auto SetInt = 0x183A0E0;
	constexpr auto SetColor = 0x1839CF0;
	constexpr auto set_shader = 0x183ACE0;
	constexpr auto get_shader = 0x183AB50;
	constexpr auto get_material = 0x18D9600;
	constexpr auto get_Renderers = 0x3FE2C0;
	constexpr auto ShaderFind = 0x18DC3F0;
	constexpr auto OnLand = 0x30E9E0; // BasePlayer->OnLand
	constexpr auto get_position = 0x736380; // playereyes->get_position
	constexpr auto IsBeingHacked = 0x2EA240;
	constexpr auto IsFullyHacked = 0x2EAA90;
	constexpr auto ForceToPos = 0x3074F0;
	constexpr auto UpdateAmbient = 0x118AF30; // public void UpdateAmbient() { } || TOD_Sky
	constexpr auto set_rayleigh = 0x82BC10;
	constexpr auto AssistPlayer = 0x30E320; // public void Menu_AssistPlayer(BasePlayer player) { }
	constexpr auto Launch = 0x5C79D0; // internal void Launch() { }
	constexpr auto KnockDoor = 0x9669A0; // public void Menu_KnockDoor(BasePlayer player) { }
	constexpr auto OpenDoor = 0x966A20; // public void Menu_OpenDoor(BasePlayer player) { }
	constexpr auto OpenHatch = 0x966A70; // public void Menu_ToggleHatch(BasePlayer player) { }
	constexpr auto IsHidden = 0x2F5360; // public class StashContainer : StorageContainer
	constexpr auto get_isHeadshot = 0x43D740; // public bool get_isHeadshot() { }
	constexpr auto DoHitNotify = 0x428200; // public void DoHitNotify(HitInfo info) { }
	constexpr auto StartAttackCooldown = 0x41DB70; // protected void StartAttackCooldown(float cooldown) { }
	constexpr auto ProcessAttack = 0x2F28A0; // protected virtual void ProcessAttack(HitTest hit) { }
	constexpr auto get_transform = 0x1826810; // public Transform get_transform() { } | UnityEngine::Component
	constexpr auto HitTest = 0x31BEDF8; // HitTest_TypeInfo
	constexpr auto ServerRPC = 0x434830;
	constexpr auto BaseNetworkable = 0x31BF748; // BaseNetworkable_TypeInfo
	constexpr auto SendProjectileAttack = 0x318290; // public void SendProjectileAttack(PlayerProjectileAttack attack) { }
	constexpr auto GetModifiedAimConeDirection = 0x989610; // public static Vector3 GetModifiedAimConeDirection(float aimCone, Vector3 inputVec, bool anywhereInside = True) { }
	constexpr auto set_flying = 0x1D0C120; // public void set_flying(bool value) { }
	constexpr auto CanAttack = 0x2FF660; // public bool CanAttack() { }
	constexpr auto SendClientTick = 0x317C00; // internal void SendClientTick() { }
	constexpr auto HandleRunning = 0xB3B7B0; // private void HandleRunning(ModelState state, bool wantsRun) { }
	constexpr auto HandleJumping = 0xB3B690;
	constexpr auto CreateProjectile = 0x73BD70; // private Projectile CreateProjectile(string prefabPath, Vector3 pos, Vector3 forward, Vector3 velocity) { }
	constexpr auto CanHoldItems = 0x2F5EA0; // public virtual bool CanHoldItems() { }
	constexpr auto Run = 0x21944E0; // public static string Run(ConsoleSystem.Option options, string strCommand, object[] args) { }
	constexpr auto DoMovement = 0x5C5F80; // private void DoMovement(float deltaTime) { }
	constexpr auto DoHit = 0x5C5890; // private bool DoHit(HitTest test, Vector3 point, Vector3 normal) { }
	constexpr auto ClientInput = 0x3017E0; // internal virtual void ClientInput(InputState state) { }
	constexpr auto ConvarGraphics = 0x31BE480; // ConVar.Graphics_TypeInfo
	constexpr auto ClosestPoint = 0x42B930; // public Vector3 ClosestPoint(Vector3 position) { }
	constexpr auto LineOfSight = 0x7F3C20; // public static bool LineOfSight(Vector3 p0, Vector3 p1, int layerMask, float padding = 0) { }
}
